ALTER TABLE users ADD COLUMN IF NOT EXISTS country_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dial_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_e164 TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone_e164 
ON users(phone_e164) 
WHERE phone_e164 IS NOT NULL AND phone_e164 != '';
